// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR5pCmR06t9GwpiHpRNxC7XEJJPFgiLIo',
    appId: '1:633726745063:web:774639afddd4eb577aa542',
    messagingSenderId: '633726745063',
    projectId: 'fbapp-7d976',
    authDomain: 'fbapp-7d976.firebaseapp.com',
    storageBucket: 'fbapp-7d976.appspot.com',
    measurementId: 'G-WGD34X8SX0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvJBNFv45YRHgPoHrMHV491Gb-N98QiJE',
    appId: '1:633726745063:android:af71fd86d598c29d7aa542',
    messagingSenderId: '633726745063',
    projectId: 'fbapp-7d976',
    storageBucket: 'fbapp-7d976.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdKxMyQQF9lROfj8-F90y_5KEVvpZ8UZw',
    appId: '1:633726745063:ios:3b5b35f98030fe1b7aa542',
    messagingSenderId: '633726745063',
    projectId: 'fbapp-7d976',
    storageBucket: 'fbapp-7d976.appspot.com',
    iosBundleId: 'com.example.mprj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdKxMyQQF9lROfj8-F90y_5KEVvpZ8UZw',
    appId: '1:633726745063:ios:ca1ed42b4b66c7d47aa542',
    messagingSenderId: '633726745063',
    projectId: 'fbapp-7d976',
    storageBucket: 'fbapp-7d976.appspot.com',
    iosBundleId: 'com.example.mprj.RunnerTests',
  );
}
